### ISSUE TITLE
Class Cast Exception on ArcChartView.kt line 698

### ISSUE THREAD

**Issue by NyiNyiLin** [imaNNeoFighT/ArcChartView#3]
<code>
Caused by java.lang.ClassCastException: java.lang.Object[] cannot be cast to java.lang.Integer[]
       at com.neo.arcchartview.ArcChartView$SavedState.<init>(ArcChartView.kt:698)
       at com.neo.arcchartview.ArcChartView$SavedState$CREATOR.createFromParcel(ArcChartView.kt:665)
       at com.neo.arcchartview.ArcChartView$SavedState$CREATOR.createFromParcel(ArcChartView.kt:664)
       at android.os.Parcel.readParcelable(Parcel.java:2777)
       at android.os.Parcel.readValue(Parcel.java:2671)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:3126)
       at android.os.Parcel.readSparseArray(Parcel.java:2354)
       at android.os.Parcel.readValue(Parcel.java:2728)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3045)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
       at android.os.BaseBundle.unparcel(BaseBundle.java:232)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:1010)
</code>

on Mi 8 (android v9), Redmi 5 plus (android v8.1.0)

**Comment by oduysmara** [comment]
i have the same issue on Note8 Samsung, any solution  for this  issue  ?
